gui_apps/django_demo_site/demo_site/art/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap

from . import views
from .feeds import ArtFeed
from .sitemaps import ArtSitemap

app_name = 'art'  # Set app name

# Define URL patterns
urlpatterns = [
    # /art/
    path('', views.index, name='art_index'),
    # /art/artists/
    path('artists/', views.artists, name='artists'),
    # /art/artwork/
    path('artwork/', views.artwork, name='artwork'),
    # /art/search/
    path('search/', views.search, name='search'),
    # /art/feed/
    path('feed/', ArtFeed(), name="art_feed"),
    # /art/sitemap.xml
    path('sitemap.xml', sitemap,
         {'sitemaps': {'art': ArtSitemap}}, name='art_sitemap'),
    # /art/artwork-recommendation/
    path('artwork-recommendation/', views.artwork_rec,
         name='artwork_rec'),
    # /art/artwork-recommendation-success/
    path('artwork-recommendation-success/',
         views.artwork_rec_succ, name='artwork_rec_succ'),
    # /art/utagawa-hiroshige/
    path('<slug:artist_slug>/', views.artist_detail, name='artist_detail'),
    # /art/utagawa-hiroshige/nihonbashi/
    path('<slug:artist_slug>/<slug:artwork_slug>/', views.artwork_detail,
         name='artwork_detail'),
]

gui_apps/django_demo_site/demo_site/demo_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('art/', include('art.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Demo Site'  # Set admin site header
admin.site.site_title = 'Demo Site'  # Set admin site head title
admin.site.index_title= 'Demo Site Administration'  # Set admin site index title
# admin.site.site_url= '/admin'  # Set admin site URL

handler404 = 'pages.views.custom_404'  # Set 404 handler

gui_apps/django_demo_site/demo_site/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'  # Set app name

# Define URL patterns
urlpatterns = [
    # /
    path('', views.index, name='home'),
    # /about/
    path('about/', views.about, name='about'),
]

gui_apps/django_demo_site/demo_site/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Django Demo Site - {{ page_title }}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="referrer" content="origin">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'images/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#00a300">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
    <script defer type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
  </head>
  <body ontouchstart="">
    <div id="body"{% if request.path == '/' %} class="home"{% endif %}>
      <header>
        <div id="header">
          <div id="titles">
            <h1 id="title"><a href="{% url 'pages:home' %}">Django Demo Site</a></h1>
            <span id="subtitle">A Django Demo Site</span>
          </div>
          <div id="search-feed">
            <div id="search">
              <span><a href="{% url 'art:search' %}">Search</a></span>
            </div>
            <div id="feed">
              <span><a href="{% url 'art:art_feed' %}">Feed</a></span>
            </div>
          </div>
          <nav>
            <div id="main-menu">
              <div class="menu-item"><a{% if request.path == '/about/' %} class="active"{% endif %} href="{% url 'pages:about' %}">About</a><span class="menu-dot">·</span></div>
              <div class="menu-item"><a{% if request.path == '/art/' %} class="active"{% endif %} href="{% url 'art:art_index' %}">Art</a><span class="menu-dot">·</span></div>
              <div class="menu-item"><a{% if request.path == '/art/artists/' %} class="active"{% endif %} href="{% url 'art:artists' %}">Artists</a><span class="menu-dot">·</span></div>
              <div class="menu-item"><a{% if request.path == '/art/artwork/' %} class="active"{% endif %} href="{% url 'art:artwork' %}">Artwork</a></div>
            </div>
          </nav>
        </div>
      </header>
      <main>
        <div id="main">
          {% block content %}{% endblock %}
        </div>
      </main>
      <footer>
        <div id="footer">
          <div id="footer-widgets">
            <div class="footer-widget"><h2><a href="https://docs.djangoproject.com/">Documentation</a></h2><span>Everything you need to know about Django.</span></div>
            <div class="footer-widget"><h2><a href="https://www.djangoproject.com/weblog/">News and Events</a></h2><span>Stay informed about the latest Django developments and events.</span></div>
            <div class="footer-widget"><h2><a href="https://www.djangoproject.com/community/">Community</a></h2><span>Get help and get involved.</span></div>
          </div>
          <p id="powered-by">Powered by <a href="https://www.djangoproject.com/">Django</a></p>
        </div>
      </footer>
    </div>
  </body>
</html>