gui_apps/django_demo_site/demo_site/art/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap

from . import views
from .feeds import ArtFeed
from .sitemaps import ArtSitemap

app_name = 'art'  # Set app name

# Define URL patterns
urlpatterns = [
    # /art/
    path('', views.index, name='art_index'),
    # /art/artists/
    path('artists/', views.artists, name='artists'),
    # /art/artwork/
    path('artwork/', views.artwork, name='artwork'),
    # /art/search/
    path('search/', views.search, name='search'),
    # /art/feed/
    path('feed/', ArtFeed(), name="art_feed"),
    # /art/sitemap.xml
    path('sitemap.xml', sitemap,
         {'sitemaps': {'art': ArtSitemap}}, name='art_sitemap'),
    # /art/artwork-recommendation/
    path('artwork-recommendation/', views.artwork_rec,
         name='artwork_rec'),
    # /art/artwork-recommendation-success/
    path('artwork-recommendation-success/',
         views.artwork_rec_succ, name='artwork_rec_succ'),
    # /art/utagawa-hiroshige/
    path('<slug:artist_slug>/', views.artist_detail, name='artist_detail'),
    # /art/utagawa-hiroshige/nihonbashi/
    path('<slug:artist_slug>/<slug:artwork_slug>/', views.artwork_detail,
         name='artwork_detail'),
]

gui_apps/django_demo_site/demo_site/demo_site/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('art/', include('art.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Demo Site'  # Set admin site header
admin.site.site_title = 'Demo Site'  # Set admin site head title
admin.site.index_title= 'Demo Site Administration'  # Set admin site index title
# admin.site.site_url= '/admin'  # Set admin site URL

handler404 = 'pages.views.custom_404'  # Set 404 handler

gui_apps/django_demo_site/demo_site/art/forms.py
'''
Define forms for the art app.

Classes:
    * RecArtworkForm - Define RecArtworkForm model.
'''
from django.forms import ModelForm, TextInput, ValidationError

from .models import Artwork, ArtworkRecommendation


class RecArtworkForm(ModelForm):
    '''
    Define RecArtworkForm model.

    Parent Classes:

        * ModelForm - Helper class that lets you create a Form class
                      from a Django model.

    Classes:

        * Meta - Give model metadata.

    Methods:

        * __repr__() - Return a string containing a printable representation
                       of an object.
        * __str__() - Return a string containing a nicely printable
                      representation of an object.
        * clean() - Confirm entered artwork does not already exist
                    in the collection.
    '''

    class Meta:
        '''Give form metadata.'''

        model = ArtworkRecommendation
        fields = ['title', 'first_name', 'last_name']
        widgets = {
            'title': TextInput(
                attrs={'placeholder': 'Enter artwork title...'}
            ),
            'first_name': TextInput(
                attrs={'placeholder': 'Enter artist first name...'}
            ),
            'last_name': TextInput(
                attrs={'placeholder': 'Enter artist last name...'}
            ),
        }

    def __repr__(self) -> str:
        '''
        Return a string containing a printable representation of an object.
        '''
        cls = type(self)
        return (
            f'{cls.__name__}('
            f'first_name={self.first_name!r}, '
            f'last_name={self.last_name!r}, '
            f'title={self.title!r}'
        )

    def __str__(self) -> str:
        '''
        Return a string containing a nicely printable representation
        of an object.
        '''
        return f'{self.title}'

    def clean(self) -> None:
        '''Confirm entered artwork does not already exist in the collection.'''
        cleaned_data = super().clean()

        title = cleaned_data.get('title').title()
        first_name = cleaned_data.get('first_name').title()
        last_name = cleaned_data.get('last_name').title()

        match = Artwork.objects.filter(
            title=title,
            artist__first_name=first_name,
            artist__last_name=last_name,
        )
        if match.exists():
            err_msg = (
                f'{title} by {first_name} {last_name} is '
                'already present in the collection.'
            )
            raise ValidationError(err_msg)

gui_apps/django_demo_site/demo_site/art/views.py
'''
Define views for the art app.

Functions:

    * index() - Return Art index page response.
    * artists() - Return Artists page response.
    * artwork() - Return Artwork page response.
    * artist_detail() - Return artist detail page response.
    * artwork_detail() - Return artwork detail page response.
    * search() - Return Search page response.
    * artwork_rec_succ() - Return Artwork Recommendation Success page response.
    * artwork_rec() - Return Artwork Recommendation page response.
'''
# Enable an iterator that sequentially returns elements
# until all iterators are exhausted
from itertools import chain
# Enable pseudo-random number generators for various distributions
import random

from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.urls import reverse

from .models import Artist, Artwork, ArtworkRecommendation
from .forms import RecArtworkForm


def index(request: HttpRequest) -> HttpResponse:
    '''
    Return Art index page response.

    Parameters
    ----------------
    request : HttpRequest
        Django HttpRequest object.

    Returns
    ----------------
    HttpResponse
        Django HttpResponse object.
    '''
    page_title = 'Art'  # Set page title

    # Grab all artwork objects
    artwork_objs = get_list_or_404(Artwork.objects)
    random.shuffle(artwork_objs)  # Shuffle artwork objects

    # If more than five pieces of artwork, grab the first five
    if len(artwork_objs) > 5:
        artwork_objs = artwork_objs[:5]

    context = {
        'page_title': page_title,
        'artwork_objs': artwork_objs
    }

    return render(request, 'art/index.html', context)


def artists(request: HttpRequest) -> HttpResponse:
    '''
    Return Artists page response.

    Parameters
    ----------------
    request : HttpRequest
        Django HttpRequest object.

    Returns
    ----------------
    HttpResponse
        Django HttpResponse object.
    '''
    page_title = 'Artists'

    artist_objs = get_list_or_404(Artist.objects)

    context = {
        'page_title': page_title,
        'artist_objs': artist_objs
    }

    return render(request, 'art/artists.html', context)


def artwork(request: HttpRequest) -> HttpResponse:
    '''
    Return Artwork page response.

    Parameters
    ----------------
    request : HttpRequest
        Django HttpRequest object.

    Returns
    ----------------
    HttpResponse
        Django HttpResponse object.
    '''
    page_title = 'Artwork'

    artwork_objs = get_list_or_404(Artwork.objects)

    context = {
        'page_title': page_title,
        'artwork_objs': artwork_objs
    }

    return render(request, 'art/artwork.html', context)


def artist_detail(request: HttpRequest, artist_slug: str) -> HttpResponse:
    '''
    Return artist detail page response.

    Parameters
    ----------------
    request : HttpRequest
        Django HttpRequest object.
    artist_slug : str
        Artist URL slug.

    Returns
    ----------------
    HttpResponse
        Django HttpResponse object.
    '''
    artist = get_object_or_404(Artist, slug=artist_slug)
    artist_artwork = get_list_or_404(Artwork.objects, artist_id=artist.id)

    page_title = f'{artist.first_name} {artist.last_name}'

    context = {
        'artist': artist,
        'artist_artwork': artist_artwork,
        'page_title': page_title
    }

    return render(request, 'art/artist-detail.html', context)


def artwork_detail(request: HttpRequest, artist_slug: str,
                   artwork_slug: str) -> HttpResponse:
    '''
    Return artwork detail page response.

    Parameters
    ----------------
    request : HttpRequest
        Django HttpRequest object.
    artist_slug : str
        Artist URL slug.
    artwork_slug : str
        Artwork URL slug.

    Returns
    ----------------
    HttpResponse
        Django HttpResponse object.
    '''
    artist = get_object_or_404(Artist, slug=artist_slug)
    artwork = get_object_or_404(Artwork, slug=artwork_slug)

    page_title = artwork.title

    context = {
        'artist': artist,
        'artwork': artwork,
        'page_title': page_title
    }

    return render(request, 'art/artwork-detail.html', context)


def search(request: HttpRequest) -> HttpResponse:
    '''
    Return Search page response.

    Parameters
    ----------------
    request : HttpRequest
        Django HttpRequest object.

    Returns
    ----------------
    HttpResponse
        Django HttpResponse object.
    '''
    query = request.GET.get('q', '')
    if query:
        query_set = (
            Q(first_name__icontains=query)
            | Q(last_name__icontains=query)
        )
        artist_rslts = Artist.objects.filter(query_set).distinct()

        query_set = Q(title__icontains=query)
        artwork_rslts = Artwork.objects.filter(query_set).distinct()

        results = list(chain(artist_rslts, artwork_rslts))
    else:
        results = []

    page_title = 'Search'

    context = {
        'query': query,
        'results': results,
        'page_title': page_title
    }

    return render(request, 'art/search.html', context)


def artwork_rec_succ(request: HttpRequest) -> HttpResponse:
    '''
    Return Artwork Recommendation Success page response.

    Parameters
    ----------------
    request : HttpRequest
        Django HttpRequest object.

    Returns
    ----------------
    HttpResponse
        Django HttpResponse object.
    '''
    page_title = 'Artwork Recommendation Success'

    succ_msg = 'Your recommendation has been successfully recorded.'
    context = {
        'page_title': page_title,
        'succ_msg': succ_msg
    }

    return render(request, 'art/artwork-recommendation-success.html', context)


def artwork_rec(request: HttpRequest) -> HttpResponse:
    '''
    Return Artwork Recommendation page response.

    Parameters
    ----------------
    request : HttpRequest
        Django HttpRequest object.

    Returns
    ----------------
    HttpResponse
        Django HttpResponse object.
    '''
    page_title = 'Artwork Recommendation'

    if request.method == 'POST':
        form = RecArtworkForm(request.POST)

        if form.is_valid():
            artwork_rec = ArtworkRecommendation()
            artwork_rec.first_name = form.cleaned_data['first_name']
            artwork_rec.last_name = form.cleaned_data['last_name']
            artwork_rec.title = form.cleaned_data['title']
            artwork_rec.save()

            return HttpResponseRedirect(reverse('art:artwork_rec_succ'))
    else:
        form = RecArtworkForm()

    context = {
        'page_title': page_title,
        'form': form
    }

    return render(request, 'art/artwork-recommendation.html', context)

gui_apps/django_demo_site/demo_site/templates/art/artist-detail.html
{% extends "base.html" %}

{% block content %}<p><a href="{{ artist.info_url }}">{{ artist.first_name }} {{ artist.last_name }}</a> was born in the year {{ artist.date_of_birth.year }} in {{ artist.country_of_origin }}.</p>{% if artist.description %}
          <details>
            <summary>Show/Hide Optional Artist Description</summary>
            <p>{{ artist.description|linebreaks }}</p>
          </details>{% endif %}
          <p>Available artwork:</p>
          <ul>{% for artwork in artist_artwork %}
            <li><a href="{{ artwork.slug }}/">{{ artwork.title }}</a></li>{% endfor %}
          </ul>{% endblock %}

gui_apps/django_demo_site/demo_site/templates/art/artists.html
{% extends "base.html" %}

{% block content %}<div id="artists">
            <h2>Artists</h2>
            <ul>{% for artist in artist_objs %}
              <li><a href="../{{ artist.slug }}/">{{ artist.first_name }} {{ artist.last_name }}</a></li>{% endfor %}
            </ul>
          </div>{% endblock %}

gui_apps/django_demo_site/demo_site/templates/art/artwork-detail.html
{% extends "base.html" %}

{% block content %}<figure id="artwork">
            <img class="shadow" alt="{{ artwork.title }}" src="{{ MEDIA_URL }}{{ artwork.image }}" width="{{ artwork.image.width }}" height="{{ artwork.image.height }}" />
            <figcaption><a href="{{ artwork.info_url }}">{{ artwork.title }}</a> by <a href="../">{{ artist.first_name }} {{ artist.last_name }}</a> ({{ artwork.pub_date.year }})</figcaption>
          </figure>{% if artwork.description %}
          <details>
            <summary>Show/Hide Optional Artwork Description</summary>
            <p>{{ artwork.description|linebreaks }}</p>
          </details>{% endif %}{% endblock %}

gui_apps/django_demo_site/demo_site/templates/art/artwork-recommendation-success.html
{% extends "base.html" %}

{% block content %}<p>{{ succ_msg }}</p>{% endblock %}

gui_apps/django_demo_site/demo_site/templates/art/artwork-recommendation.html
{% extends "base.html" %}

{% block content %}<p>Complete the form to recommend a piece of artwork for the collection.</p>
          <form action="" method="post">
            {% csrf_token %}{{ form.non_field_errors }}{% for field in form %}
            <div class="form-elem">
              {{ field.errors }}
              <label>{{ field.label }}:</label> {{ field }}
            </div>{% endfor %}
            <div class="form-elem">
              <input name="artwork-recommendation" type="submit" value="Submit">
            </div>
          </form>{% endblock %}

gui_apps/django_demo_site/demo_site/templates/art/artwork.html
{% extends "base.html" %}

{% block content %}<div id="artwork">
            <h2>Artwork</h2>
            <ul>{% for artwork in artwork_objs %}
              <li><a href="../{{ artwork.artist.slug }}/{{ artwork.slug }}/">{{ artwork.title }}</a></li>{% endfor %}
            </ul>
            <p>To suggest a piece of artwork for the collection, leave a <a href="{% url 'art:artwork_rec' %}">recommendation</a>.</p>
          </div>{% endblock %}

gui_apps/django_demo_site/demo_site/templates/art/index.html
{% extends "base.html" %}

{% block content %}<blockquote cite="https://www.goodreads.com/quotes/31333-it-is-good-to-love-many-things-for-therein-lies"><p>It is good to love many things, for therein lies the true strength, and whosoever loves much performs much, and can accomplish much, and what is done in love is well done.</p><footer>- Vincent van Gogh</footer></blockquote>
          <p>Artwork to explore:</p>
          <ul>
            {% for artwork in artwork_objs %}<li><a href="{{ artwork.artist.slug }}/{{ artwork.slug }}/">{{ artwork.title }}</a></li>{% endfor %}
          </ul>{% endblock %}

gui_apps/django_demo_site/demo_site/templates/art/search.html
{% extends "base.html" %}

{% block content %}<p>Search by <strong>artist name</strong> or <strong>artwork title</strong>.</p>
          <form action="." method="get">
            <input name="q" type="text" placeholder="Search...">
            <!-- <input type="submit" value="{{ query|escape }}"/> -->
          </form>{% if query %}{% if results %}
          <ul>{% for obj in results %}{% if obj.first_name %}
            <li><a href="../{{ obj.slug }}/">{{ obj|escape }}</a></li>{% elif obj.title %}
            <li><a href="../{{ obj.artist.slug }}/{{ obj.slug }}/">{{ obj | escape }}</a></li>{% endif %}{% endfor %}
          </ul>{% else %}
          <p>Query returned no results.</p>{% endif %}{% endif %}{% endblock %}